import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Đọc dữ liệu
file_path = r"D:\HUST-MI2\2025.2\Đồ án 1-Thầy Đoàn Duy Trung\Data\superstore_cleaned.csv"
df = pd.read_csv(file_path, encoding="utf-8-sig")
df["Order Date"] = pd.to_datetime(df["Order Date"], errors="coerce")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], errors="coerce")
pd.set_option("display.max_columns", None)
sns.set(style="whitegrid")
print("Kích thước dữ liệu:", df.shape)
print("\n5 dòng đầu:")
print(df.head())
# 2. Thống kê tổng quan
print("\nTổng doanh số:", df["Sales"].sum())
print("Tổng lợi nhuận:", df["Profit"].sum())
print("Tổng số lượng bán:", df["Quantity"].sum())
print("Số khách hàng:", df["Customer ID"].nunique())
print("Số sản phẩm:", df["Product ID"].nunique())
# 3. Phân tích doanh số theo thời gian
sales_by_month = df.groupby(["Year", "Month"], as_index=False)["Sales"].sum()
sales_by_month["Year-Month"] = sales_by_month["Year"].astype(str) + "-" + sales_by_month["Month"].astype(str).str.zfill(2)
print("\nDoanh số theo tháng:")
print(sales_by_month.head(12))
plt.figure(figsize=(12, 6))
plt.plot(sales_by_month["Year-Month"], sales_by_month["Sales"], marker="o")
plt.xticks(rotation=45)
plt.title("Doanh số theo thời gian")
plt.xlabel("Tháng")
plt.ylabel("Doanh số")
plt.tight_layout()
plt.show()
# 4. Phân tích theo khu vực
region_summary = df.groupby("Region", as_index=False)[["Sales", "Profit"]].sum().sort_values(by="Sales", ascending=False)
print("\nDoanh số và lợi nhuận theo khu vực:")
print(region_summary)
plt.figure(figsize=(10, 6))
sns.barplot(data=region_summary, x="Region", y="Sales")
plt.title("Doanh số theo khu vực")
plt.xlabel("Khu vực")
plt.ylabel("Doanh số")
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 6))
sns.barplot(data=region_summary, x="Region", y="Profit")
plt.title("Lợi nhuận theo khu vực")
plt.xlabel("Khu vực")
plt.ylabel("Lợi nhuận")
plt.tight_layout()
plt.show()
# 5. Phân tích theo danh mục sản phẩm
category_summary = df.groupby("Category", as_index=False)[["Sales", "Profit"]].sum().sort_values(by="Sales", ascending=False)
print("\nDoanh số và lợi nhuận theo danh mục:")
print(category_summary)
plt.figure(figsize=(10, 6))
sns.barplot(data=category_summary, x="Category", y="Sales")
plt.title("Doanh số theo danh mục sản phẩm")
plt.xlabel("Danh mục")
plt.ylabel("Doanh số")
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 6))
sns.barplot(data=category_summary, x="Category", y="Profit")
plt.title("Lợi nhuận theo danh mục sản phẩm")
plt.xlabel("Danh mục")
plt.ylabel("Lợi nhuận")
plt.tight_layout()
plt.show()
# 6. Phân tích theo phân khúc khách hàng
segment_summary = df.groupby("Segment", as_index=False)[["Sales", "Profit"]].sum().sort_values(by="Sales", ascending=False)
print("\nDoanh số và lợi nhuận theo phân khúc khách hàng:")
print(segment_summary)
plt.figure(figsize=(10, 6))
sns.barplot(data=segment_summary, x="Segment", y="Sales")
plt.title("Doanh số theo phân khúc khách hàng")
plt.xlabel("Phân khúc")
plt.ylabel("Doanh số")
plt.tight_layout()
plt.show()
# 7. Top 10 sản phẩm có doanh số cao nhất
top_products = df.groupby("Product Name", as_index=False)["Sales"].sum().sort_values(by="Sales", ascending=False).head(10)
print("\nTop 10 sản phẩm có doanh số cao nhất:")
print(top_products)
plt.figure(figsize=(12, 6))
sns.barplot(data=top_products, x="Sales", y="Product Name")
plt.title("Top 10 sản phẩm có doanh số cao nhất")
plt.xlabel("Doanh số")
plt.ylabel("Sản phẩm")
plt.tight_layout()
plt.show()
# 8. Ảnh hưởng của chiết khấu đến lợi nhuận
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x="Discount", y="Profit")
plt.title("Mối quan hệ giữa chiết khấu và lợi nhuận")
plt.xlabel("Chiết khấu")
plt.ylabel("Lợi nhuận")
plt.tight_layout()
plt.show()
discount_profit = df.groupby("Discount", as_index=False)["Profit"].mean().sort_values(by="Discount")
print("\nLợi nhuận trung bình theo mức chiết khấu:")
print(discount_profit)
plt.figure(figsize=(10, 6))
sns.lineplot(data=discount_profit, x="Discount", y="Profit", marker="o")
plt.title("Lợi nhuận trung bình theo mức chiết khấu")
plt.xlabel("Chiết khấu")
plt.ylabel("Lợi nhuận trung bình")
plt.tight_layout()
plt.show()
# 9. Phân tích thời gian giao hàng
shipping_summary = df["Shipping Days"].describe()
print("\nThống kê thời gian giao hàng:")
print(shipping_summary)
plt.figure(figsize=(10, 6))
sns.histplot(df["Shipping Days"], bins=12, kde=True)
plt.title("Phân bố thời gian giao hàng")
plt.xlabel("Số ngày giao hàng")
plt.ylabel("Tần suất")
plt.tight_layout()
plt.show()